spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev

cors:
  allowed-origin-patterns:
    - http://localhost:5173
    - http://localhost:8080
    - https://career-pirates-resumate-git-main-seeunjungs-projects.vercel.app
  allowed-origin-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-origin-headers:
    - "*"
