spring:
  application:
    name: resumate-backend
  config:
    activate:
      on-profile: dev
  docker:
    compose:
      file: ./docker-compose.local.yaml
      lifecycle-management: start_only
  data:
    redis:
      host: localhost
      port: 16379
  datasource:
    url: jdbc:postgresql://localhost:15432/resumate
    username: career
    password: pirate123!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 500
  cloud:
    aws:
      secretsmanager:
        enabled: false

oauth:
  login-redirect-url: http://localhost:5173

jwt:
  secret: b0a4ff363885bcc010ab2d331ab5f3d957f7e8aa8233a175d039acd1c2affd45
  expiration:
    access: 3600
    refresh: 2592000

cookie:
  domain: localhost

openai:
  api-key: ${OPENAI_API_KEY}
  base-url: https://api.openai.com/v1
  prompt:
    id: pmpt_68b69bf0c14081959f3bab045f17ccc803b70565310d26f7
    version: 2
