spring:
  application:
    name: resumate-backend
  config:
    activate:
      on-profile: prod
    import: "aws-secretsmanager:prod/resumate-db-credentials"
  docker:
    compose:
      file: ./docker-compose.prod.yaml
      lifecycle-management: start_only
  data:
    redis:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 500

oauth:
  login-redirect-url: ${LOGIN_REDIRECT_URL}
cors:
jwt:

cookie:
  domain: ${COOKIE_DOMAIN}
