spring:
  application:
    name: resumate-backend
  config:
    activate:
      on-profile: prod
    import: optional:file:.env[.properties]
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 500

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-methods: ${CORS_ALLOWED_METHODS}
  allowed-headers: ${CORS_ALLOWED_HEADERS}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-duration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration-duration: ${JWT_REFRESH_TOKEN_EXPIRATION}

cookie:
  domain: localhost
