spring:
  application:
    name: resumate-backend
  config:
    activate:
      on-profile: prod
  docker:
    compose:
      file: ./docker-compose.prod.yaml
      lifecycle-management: start_only
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 500

oauth:
  login-redirect-url: ${LOGIN_REDIRECT_URL}

cors:
  allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS}
  allowed-origin-methods: ${CORS_ALLOWED_METHODS}
  allowed-origin-headers: "*"

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refresh: ${JWT_REFRESH_TOKEN_EXPIRATION}

cookie:
  domain: ${COOKIE_DOMAIN}

openai:
  api-key: ${OPENAI_API_KEY}
  base-url: https://api.openai.com/v1
  prompt:
    id: pmpt_68b69bf0c14081959f3bab045f17ccc803b70565310d26f7
    version: 2
