spring:
  application:
    name: resumate-backend
  config:
    activate:
      on-profile: prod
    import: "aws-secretsmanager:prod/resumate-db-credentials"
  docker:
    compose:
      file: ./docker-compose.prod.yaml
      lifecycle-management: start_only
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 500
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: Google
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: https://api.resu.monster/login/oauth2/code/google
            scope: email
          naver:
            client-name: Naver
            client-id: ${NAVER_OAUTH2_CLIENT_ID}
            client-secret: ${NAVER_OAUTH2_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: https://api.resu.monster/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: email
          kakao:
            client-name: Kakao
            client-id: ${KAKAO_OAUTH2_CLIENT_ID}
            client-secret: ${KAKAO_OAUTH2_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: https://api.resu.monster/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: account_email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

oauth:
  login-redirect-url: ${LOGIN_REDIRECT_URL}

cors:
  allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS}
  allowed-origin-headers: ${CORS_ALLOWED_HEADERS}
  allowed-origin-methods: ${CORS_ALLOWED_METHODS}
jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refresh: ${JWT_REFRESH_TOKEN_EXPIRATION}

cookie:
  domain: ${COOKIE_DOMAIN}

openai:
  api-key: ${OPENAI_API_KEY}
  base-url: https://api.openai.com/v1
  prompt: ${OPENAI_PROMPT}
