spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
  metrics:
    tags:
      application: resumate-backend
  prometheus:
    metrics:
      export:
        enabled: true

cors:
  allowed-origin-patterns:
    - http://localhost:5173
    - http://localhost:8080
    - https://career-pirates-resumate.vercel.app
  allowed-origin-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-origin-headers:
    - "*"
