name: PR Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [develop]
    paths:
      - 'src/**'
      - 'build.gradle'
      - 'settings.gradle'
      - 'gradle.properties'
      - 'gradle/**'
      - 'gradlew*'
      - '.github/workflows/pr-tests.yml'
  workflow_dispatch:

concurrency:
  group: pr-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Unit Tests (Java 17)
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 20
    permissions:
      contents: read
      pull-requests: write
      checks: write

    env:
      SPRING_PROFILES_ACTIVE: test
      OPENAI_API_KEY: test
      JWT_SECRET: test-secret-32bytes-minimum-padding-123456
      AWS_EC2_METADATA_DISABLED: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Validate Gradle wrapper (best-effort)
#        uses: gradle/wrapper-validation-action@v2
#        continue-on-error: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run tests
        run: ./gradlew --no-daemon clean test

      - name: Upload test reports (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/test

      - name: Publish JUnit results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: JUnit Tests
          path: build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: false